server:
  port: 9695
spring:
  banner:
    location: classpath:DialerBanner.txt
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/dialer
    username: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        hbm2ddl:
          auto: update
        show_sql: false
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
  
            
            
#Zing props
zing:
  authToken: e2f1c3a7984d49b7b21b39fdb92b0934
  fromNumber: '+18477871945'
  hideCallerId: false
  sid: AC777c3e3273a9f4b188f44fecba72d1d6
  statusCallbackUrl: https://c00f-2405-201-6005-fdcc-608f-7fdc-879e-83cb.in.ngrok.io/
  timeout: 30
  url: https://zang.io/ivr/welcome/call
