server:
  port: 9695
spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/voicera_assesment
    username: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#        format_sql: true
        hbm2ddl:
          auto: update
        show_sql: true
